import type { TodayTeamOption } from '../components/today/TodayPersonalizationPanel';

export const MLB_TEAM_OPTIONS: TodayTeamOption[] = [
  { id: 108, abbreviation: 'LAA', name: 'Los Angeles Angels' },
  { id: 109, abbreviation: 'ARI', name: 'Arizona Diamondbacks' },
  { id: 110, abbreviation: 'BAL', name: 'Baltimore Orioles' },
  { id: 111, abbreviation: 'BOS', name: 'Boston Red Sox' },
  { id: 112, abbreviation: 'CHC', name: 'Chicago Cubs' },
  { id: 113, abbreviation: 'CIN', name: 'Cincinnati Reds' },
  { id: 114, abbreviation: 'CLE', name: 'Cleveland Guardians' },
  { id: 115, abbreviation: 'COL', name: 'Colorado Rockies' },
  { id: 116, abbreviation: 'DET', name: 'Detroit Tigers' },
  { id: 117, abbreviation: 'HOU', name: 'Houston Astros' },
  { id: 118, abbreviation: 'KC', name: 'Kansas City Royals' },
  { id: 119, abbreviation: 'LAD', name: 'Los Angeles Dodgers' },
  { id: 120, abbreviation: 'WSH', name: 'Washington Nationals' },
  { id: 121, abbreviation: 'NYM', name: 'New York Mets' },
  { id: 133, abbreviation: 'ATH', name: 'Athletics' },
  { id: 134, abbreviation: 'PIT', name: 'Pittsburgh Pirates' },
  { id: 135, abbreviation: 'SD', name: 'San Diego Padres' },
  { id: 136, abbreviation: 'SEA', name: 'Seattle Mariners' },
  { id: 137, abbreviation: 'SF', name: 'San Francisco Giants' },
  { id: 138, abbreviation: 'STL', name: 'St. Louis Cardinals' },
  { id: 139, abbreviation: 'TB', name: 'Tampa Bay Rays' },
  { id: 140, abbreviation: 'TEX', name: 'Texas Rangers' },
  { id: 141, abbreviation: 'TOR', name: 'Toronto Blue Jays' },
  { id: 142, abbreviation: 'MIN', name: 'Minnesota Twins' },
  { id: 143, abbreviation: 'PHI', name: 'Philadelphia Phillies' },
  { id: 144, abbreviation: 'ATL', name: 'Atlanta Braves' },
  { id: 145, abbreviation: 'CWS', name: 'Chicago White Sox' },
  { id: 146, abbreviation: 'MIA', name: 'Miami Marlins' },
  { id: 147, abbreviation: 'NYY', name: 'New York Yankees' },
  { id: 158, abbreviation: 'MIL', name: 'Milwaukee Brewers' },
];
