export const z8Profile = {
  panel: 'rounded-2xl border border-white/10 bg-white/[0.03]',
  panelSoft: 'rounded-2xl border border-white/10 bg-black/30',
  label: 'text-[9px] font-black uppercase tracking-[0.18em] text-white/40',
  labelCyan: 'text-[10px] font-black uppercase tracking-[0.18em] text-vouch-cyan',
  value: 'text-2xl font-extrabold tabular-nums text-white',
  muted: 'text-white/40',
  row: 'border-t border-white/10 bg-white/[0.03]',
  rowDark: 'border-t border-white/10 bg-ve-obsidian',
  warningPanel: 'rounded-xl border border-amber-400/25 bg-amber-400/[0.07]',
  successText: 'text-emerald-300',
  dangerText: 'text-rose-400',
  cyanText: 'text-vouch-cyan',
  goldText: 'text-amber-300',
};
