import {
  Activity,
  BarChart3,
  ClipboardCheck,
  Crown,
  Flame,
  LayoutDashboard,
  ListChecks,
  ScanLine,
  ShieldCheck,
  Sliders,
  Trophy,
  Users,
  Zap,
} from 'lucide-react';
import type { EdgePortalFeature } from './edgePortalTypes';

export const EDGE_PORTAL_FEATURES: EdgePortalFeature[] = [
  {
    id: 'daily_players',
    title: "Today's Player Board",
    eyebrow: 'Find today’s edge',
    subtitle: 'Matchups, lineups, starters, and projected hitters.',
    section: 'daily_players',
    group: 'today',
    badge: 'Live',
    priority: 10,
    enabled: true,
    icon: Users,
  },
  {
    id: 'today',
    title: 'Command Center',
    eyebrow: 'Start here',
    subtitle: 'Your daily MLB dashboard and top slate overview.',
    section: 'today',
    group: 'today',
    priority: 20,
    enabled: true,
    icon: LayoutDashboard,
  },
  {
    id: 'hr_board',
    title: 'HR Edge Board',
    eyebrow: 'Power spots',
    subtitle: 'Find vulnerable pitchers and homerun angles.',
    section: 'hr_board',
    group: 'today',
    badge: 'Hot',
    priority: 30,
    enabled: true,
    icon: Flame,
  },
  {
    id: 'live_games',
    title: 'Live Games',
    eyebrow: 'In-game pulse',
    subtitle: 'Track today’s game states and live momentum.',
    section: 'live_games',
    group: 'today',
    priority: 40,
    enabled: true,
    icon: Activity,
  },
  {
    id: 'parlay_lab',
    title: 'Build Smarter Parlay',
    eyebrow: 'Build',
    subtitle: 'Create slips with risk tiers and cleaner logic.',
    section: 'build',
    group: 'build',
    priority: 50,
    enabled: true,
    icon: Sliders,
  },
  {
    id: 'scan_slip',
    title: 'Scan My Slip',
    eyebrow: 'Upload',
    subtitle: 'Review a ticket and catch weak legs before saving.',
    section: 'board',
    group: 'build',
    priority: 60,
    enabled: true,
    icon: ScanLine,
  },
  {
    id: 'my_parlays',
    title: 'My Parlays',
    eyebrow: 'Saved',
    subtitle: 'Open your saved slips, history, and active cards.',
    section: 'build',
    group: 'build',
    priority: 70,
    enabled: true,
    icon: ClipboardCheck,
  },
  {
    id: 'results',
    title: 'Track Your Proof',
    eyebrow: 'Proof',
    subtitle: 'Results, grading, hit rate, and trust history.',
    section: 'results',
    group: 'proof',
    priority: 80,
    enabled: true,
    icon: BarChart3,
  },
  {
    id: 'ledger',
    title: 'Pick Ledger',
    eyebrow: 'Receipts',
    subtitle: 'Your win/loss record and public proof system.',
    section: 'results',
    group: 'proof',
    priority: 90,
    enabled: true,
    icon: ListChecks,
  },
  {
    id: 'cappers',
    title: 'Verified Cappers',
    eyebrow: 'Community',
    subtitle: 'Ranked creators, proof profiles, and trust scores.',
    section: 'leaderboard',
    group: 'proof',
    priority: 100,
    enabled: true,
    icon: Trophy,
  },
  {
    id: 'pro_research',
    title: 'Unlock Pro Research',
    eyebrow: 'Pro',
    subtitle: 'Deep graphs, matchup history, and premium alerts.',
    section: 'research',
    group: 'pro',
    badge: 'Pro',
    requiresPro: true,
    priority: 110,
    enabled: true,
    icon: Crown,
  },
  {
    id: 'ai_tools',
    title: 'AI Judge Notes',
    eyebrow: 'AI Seat',
    subtitle: 'Ask VouchEdge AI what to open or study next.',
    section: 'intel',
    group: 'pro',
    badge: 'AI',
    priority: 120,
    enabled: true,
    icon: Zap,
  },
  {
    id: 'trust',
    title: 'Trust System',
    eyebrow: 'Safety',
    subtitle: 'Transparent grading, sources, and proof-first design.',
    section: 'board',
    group: 'system',
    priority: 130,
    enabled: true,
    icon: ShieldCheck,
  },
];

export const EDGE_PORTAL_GROUP_LABELS: Record<EdgePortalFeature['group'], string> = {
  today: "Today's Edge",
  build: 'Build',
  proof: 'Proof',
  pro: 'Pro + AI',
  system: 'Trust System',
};
