import React from 'react';
import { MLBPlayer, Vouch } from '../../types';

export interface CustomPlayerSelection {
  player: MLBPlayer;
  statType: 'Homeruns' | 'Runs' | 'Hits' | 'RBIs' | 'AVG' | 'OPS';
  customVal: string;
  aiConfidence?: number;
  playerConfidence?: number;
  customExplanation?: string;
  // Spotlight Analytical Additions
  pitcherName?: string;
  pitcherHand?: 'RHP' | 'LHP';
  hitRateLast10?: number;
  playRatePercent?: number;
  pitchTypeFavored?: string;
  pitcherEra?: number;
  edgeMathProof?: string;
}

export type CardStyleId = 'cyberpunk' | 'luxury' | 'crimson' | 'minimal' | 'hologram';
export type CardLayoutId = 'orbit' | 'potd' | 'parlay';

export interface CardStyleConfig {
  bg: string;
  cardBorder: string;
  radialGrad: string;
  cornerLight1: string;
  cornerLight2: string;
  orbitStroke: string;
  orbitDashed: string;
  orbitRing: string;
  hubBg: string;
  hubGlow: string;
  hubVeBg: string;
  hubText: string;
  nodeBorder: string;
  nodeValueBg: string;
  nodeTagBg: string;
  reasonsBg: string;
  headerTitleColor: string;
  headerSubTitleColor: string;
  brandBadge: string;
  activeLineColor1: string;
  activeLineColor2: string;
  ambientPingColor: string;
  labelText: string;
  labelText2: string;
  footerUrlColor: string;
  footerPingColor: string;
}

export interface VouchStudioDarkroomProps {
  profile: any;
  savedVouches: Vouch[];
  selectedPlayers: CustomPlayerSelection[];
  setSelectedPlayers: React.Dispatch<React.SetStateAction<CustomPlayerSelection[]>>;
  cardStyle: CardStyleId;
  setCardStyle: (style: CardStyleId) => void;
  activeCardLayout: CardLayoutId;
  setActiveCardLayout: (layout: CardLayoutId) => void;
  potdIndex: number;
  setPotdIndex: (idx: number) => void;
  customCardPhoto: string;
  setCustomCardPhoto: (url: string) => void;
  customCardPhotoLabel: string;
  setCustomCardPhotoLabel: (label: string) => void;
  showWinRate: boolean;
  setShowWinRate: (show: boolean) => void;
  customWinRate: string;
  setCustomWinRate: (val: string) => void;
  showDailyWinRate: boolean;
  setShowDailyWinRate: (show: boolean) => void;
  customDailyWinRate: string;
  setCustomDailyWinRate: (val: string) => void;
  showMonthlyWinRate: boolean;
  setShowMonthlyWinRate: (show: boolean) => void;
  customMonthlyWinRate: string;
  setCustomMonthlyWinRate: (val: string) => void;
  showMlbPicks: boolean;
  setShowMlbPicks: (show: boolean) => void;
  customMlbPicks: string;
  setCustomMlbPicks: (val: string) => void;
  showProBadge: boolean;
  setShowProBadge: (show: boolean) => void;
  customProTag: string;
  setCustomProTag: (val: string) => void;
  showUnitsProfit: boolean;
  setShowUnitsProfit: (show: boolean) => void;
  unitsProfitValue: string;
  setUnitsProfitValue: (val: string) => void;
  showBestParlay: boolean;
  setShowBestParlay: (show: boolean) => void;
  bestParlayDesc: string;
  setBestParlayDesc: (val: string) => void;
  showCoupon: boolean;
  setShowCoupon: (show: boolean) => void;
  couponCode: string;
  setCouponCode: (val: string) => void;
  couponText: string;
  setCouponText: (val: string) => void;
  reasonsText: string;
  setReasonsText: (val: string) => void;
  showCharts: boolean;
  setShowCharts: (show: boolean) => void;
  showLogo: boolean;
  setShowLogo: (show: boolean) => void;
  showReasons: boolean;
  setShowReasons: (show: boolean) => void;
  previewScale: number;
  setPreviewScale: (scale: number) => void;
  activePreviewCardIndex: number;
  setActivePreviewCardIndex: (idx: number) => void;
  showSecondCard: boolean;
  setShowSecondCard: (show: boolean) => void;
  postSideways: boolean;
  setPostSideways: (side: boolean) => void;
  isPublishingToFeed: boolean;
  handlePublishAsFeedPost: () => void;
  handleSimulateXPost: () => void;
  triggerToast: (msg: string) => void;
  formattedToday: string;
  calculateOrbitPos: (index: number) => { x: number; y: number };
  handleAddPlayerToCircle: (player: MLBPlayer) => void;
  handleRemovePlayerFromCircle: (playerId: string) => void;
  handleStatTypeChange: (index: number, newStat: CustomPlayerSelection['statType']) => void;
  handleCustomValChange: (index: number, text: string) => void;
  studioSectionPreset: boolean;
  setStudioSectionPreset: (val: boolean) => void;
  studioSectionRoster: boolean;
  setStudioSectionRoster: (val: boolean) => void;
  studioSectionPromo: boolean;
  setStudioSectionPromo: (val: boolean) => void;
  studioSectionRationale: boolean;
  setStudioSectionRationale: (val: boolean) => void;
}
