export interface VisualTheme {
  id: string;
  name: string;
  category: 'Core' | 'Sport' | 'Flex' | 'Retro' | 'Premium' | 'Trust' | 'Seasonal' | 'Minimal' | 'VouchEdge';
  rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'verified' | 'founder' | 'seasonal';
  description: string;
  
  // Design styles
  background: string; // page background class
  backgroundPattern?: string; // pattern type 'grid' | 'court' | 'stadium' | 'arcade' | 'pixel-zig' | 'minimal' | 'glass'
  cardStyle: string; // main card container style
  borderStyle: string; // border utility class
  glowStyle: string; // shadow glow utility class
  buttonStyle: string; // primary action button
  badgeStyle: string; // indicator tags
  sidebarStyle: string; // navigation panel overrides
  vouchCardStyle: string; // Feed vouch styles
  parlayCardStyle: string; // Parlay slip styles
  resultCardStyle: string; // Settlement cards
  profileBorderStyle: string; // profile card border overrides
  animationStyle: string; // transition and animation flags
  shareCardStyle: string; // metadata preview colors
  
  // Mechanics
  unlockCondition: string;
  isPremium: boolean;
  isEarned: boolean;
  isSeasonal: boolean;
  cost: number;
  badge: string; // small label, e.g. "🏀 COURT"
  avatarAnimationClass: string;
  particleDemo: string[];
  fontFamily: string;
  coverBg: string;
  customAIPhrase?: string;
  pageBg: string;
  gridOverlay?: string;
  borderColor?: string;
  accentText: string;
}

export interface ProfileBorder {
  id: string;
  name: string;
  rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'verified' | 'founder' | 'seasonal';
  category: string;
  themeId?: string;
  animationType: 'none' | 'pulse' | 'spin' | 'float' | 'flame' | 'sparkle';
  unlockCondition: string;
  isPremium: boolean;
  isEarned: boolean;
  description: string;
  borderClass: string; // CSS styling representing the border
  overlayIcon?: string; // Optional overlay emoji or SVG indicator
}

export const THEME_REGISTRY: VisualTheme[] = [
  {
    id: 'storm-radar',
    name: 'Storm Radar',
    category: 'VouchEdge',
    rarity: 'legendary',
    description: 'Dark radar glass with electric cyan, violet storm glow, and sharper contrast. Built for live matchup scanning and premium research sessions.',
    background: 'bg-[#020617]',
    backgroundPattern: 'radar',
    cardStyle: 'bg-[#07111f]/92 border-cyan-300/45 shadow-[0_0_34px_rgba(103,232,249,0.18)] backdrop-blur-xl',
    borderStyle: 'border-cyan-300/45',
    glowStyle: 'shadow-cyan-300/20',
    buttonStyle: 'bg-gradient-to-r from-cyan-300 to-violet-400 hover:from-cyan-200 hover:to-fuchsia-300 text-slate-950 font-black',
    badgeStyle: 'bg-cyan-400/10 text-cyan-200 border-cyan-300/35',
    sidebarStyle: 'bg-[#020617]/90 border-r border-cyan-300/16',
    vouchCardStyle: 'bg-[#07111f]/95 border-cyan-300/45 shadow-[0_0_16px_rgba(103,232,249,0.14)]',
    parlayCardStyle: 'bg-[#07111f]/95 border-cyan-300/45',
    resultCardStyle: 'bg-[#06101e]/95 border-cyan-300/28',
    profileBorderStyle: 'border-cyan-300',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-[#082f49] via-[#111827] to-[#020617]',
    unlockCondition: 'Free — included with the VouchEdge theme foundation',
    isPremium: false,
    isEarned: false,
    isSeasonal: false,
    cost: 0,
    badge: '🌩️ RADAR',
    avatarAnimationClass: 'border-cyan-300 shadow-md shadow-cyan-300/45',
    particleDemo: ['🌩️', '📡', '⚡', '🔵'],
    fontFamily: 'font-sans',
    coverBg: 'from-cyan-300/25 via-violet-400/20 to-fuchsia-400/15',
    customAIPhrase: '🌩️ STORM RADAR • LIVE EDGE SIGNALS ONLINE',
    pageBg: 'bg-[#020617]',
    gridOverlay: 'opacity-15 bg-[radial-gradient(#67e8f9_1px,transparent_1px)] [background-size:22px_22px]',
    borderColor: 'border-cyan-300/30',
    accentText: 'text-cyan-200'
  },
  {
    id: 'vouchedge-prime',
    name: 'VouchEdge Prime',
    category: 'Premium',
    rarity: 'legendary',
    description: 'The official VouchEdge flagship. Electric cyan-to-indigo dark mode with premium glow, built for serious research sessions.',
    background: 'bg-[#050B18]',
    backgroundPattern: 'grid',
    cardStyle: 'bg-[#0b1224]/90 border-[#00B7FF]/35 shadow-[0_0_28px_rgba(0,183,255,0.18)] backdrop-blur-md',
    borderStyle: 'border-[#00B7FF]/35',
    glowStyle: 'shadow-[#00B7FF]/15',
    buttonStyle: 'bg-gradient-to-r from-[#00B7FF] to-[#2563EB] hover:from-[#22D3EE] hover:to-[#00B7FF] text-slate-950 font-black',
    badgeStyle: 'bg-[#00B7FF]/10 text-[#00B7FF] border-[#00B7FF]/35',
    sidebarStyle: 'bg-[#050b18]/95 border-r border-[#00B7FF]/12',
    vouchCardStyle: 'bg-[#0b1224] border-[#00B7FF]/35 shadow-[0_0_12px_rgba(0,183,255,0.12)]',
    parlayCardStyle: 'bg-[#0b1224] border-[#00B7FF]/35',
    resultCardStyle: 'bg-[#0a1120] border-[#00B7FF]/25',
    profileBorderStyle: 'border-[#00B7FF]',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-[#062033] to-[#050B18]',
    unlockCondition: 'Free — the official default VouchEdge theme',
    isPremium: false,
    isEarned: false,
    isSeasonal: false,
    cost: 0,
    badge: '⚡ PRIME',
    avatarAnimationClass: 'border-[#00B7FF] shadow-md shadow-[#00B7FF]/40',
    particleDemo: ['⚡', '🔵', '✨', '🎯'],
    fontFamily: 'font-sans',
    coverBg: 'from-[#00B7FF]/25 to-[#2563EB]/20',
    customAIPhrase: '⚡ VOUCHEDGE PRIME • AI RESEARCH ENGINE ENGAGED',
    pageBg: 'bg-[#050B18]',
    gridOverlay: 'opacity-10 bg-[radial-gradient(#00B7FF_1px,transparent_1px)] [background-size:20px_20px]',
    borderColor: 'border-[#00B7FF]/25',
    accentText: 'text-[#00B7FF]'
  },
  {
    id: 'sharp-syndicate',
    name: 'Sharp Syndicate',
    category: 'Premium',
    rarity: 'epic',
    description: 'Deep obsidian black and amber gold for the professional analyst. Quiet, sharp, and built around probability — not hype.',
    background: 'bg-[#090600]',
    backgroundPattern: 'grid',
    cardStyle: 'bg-[#0f0a00]/95 border-amber-500/45 shadow-[0_0_32px_rgba(245,158,11,0.2)] backdrop-blur-md',
    borderStyle: 'border-amber-500/45',
    glowStyle: 'shadow-amber-500/15',
    buttonStyle: 'bg-gradient-to-r from-amber-400 to-yellow-600 hover:from-amber-300 hover:to-yellow-500 text-slate-950 font-black',
    badgeStyle: 'bg-amber-950/80 text-amber-400 border-amber-800/45',
    sidebarStyle: 'bg-[#0a0700] border-r border-amber-500/12',
    vouchCardStyle: 'bg-[#140d00] border-amber-500/45 shadow-[0_0_12px_rgba(245,158,11,0.12)]',
    parlayCardStyle: 'bg-[#140d00] border-amber-500/45',
    resultCardStyle: 'bg-[#120b00] border-amber-500/25',
    profileBorderStyle: 'border-amber-500',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-amber-950 to-[#090600]',
    unlockCondition: '500 VouchCoins or Elite membership',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 500,
    badge: '💎 SYNDICATE',
    avatarAnimationClass: 'border-amber-500 shadow-md shadow-amber-500/40',
    particleDemo: ['💎', '📊', '⚡', '🎯'],
    fontFamily: 'font-sans',
    coverBg: 'from-amber-600/30 to-yellow-500/20',
    customAIPhrase: '💎 SHARP EDGE • PROFESSIONAL PROBABILITY METRICS LOADED',
    pageBg: 'bg-[#090600]',
    gridOverlay: 'opacity-12 bg-[radial-gradient(#f59e0b_1px,transparent_1px)] [background-size:22px_22px]',
    borderColor: 'border-amber-500/25',
    accentText: 'text-amber-400'
  },
  {
    id: 'diamond-club',
    name: 'Diamond Club',
    category: 'Premium',
    rarity: 'legendary',
    description: 'Ice white and diamond blue. Clarity over noise — a high-precision interface for the most disciplined researchers.',
    background: 'bg-[#030814]',
    backgroundPattern: 'glass',
    cardStyle: 'bg-[#081028]/95 border-sky-300/55 shadow-[0_0_40px_rgba(148,216,255,0.25)] backdrop-blur-md',
    borderStyle: 'border-sky-300/55',
    glowStyle: 'shadow-sky-300/20',
    buttonStyle: 'bg-gradient-to-r from-[#94D8FF] to-[#38BDF8] hover:from-[#BAE6FD] hover:to-[#94D8FF] text-slate-950 font-black',
    badgeStyle: 'bg-sky-950/80 text-sky-200 border-sky-700/45',
    sidebarStyle: 'bg-[#040a18]/95 border-r border-sky-300/12',
    vouchCardStyle: 'bg-[#06122e] border-sky-300/55 shadow-[0_0_12px_rgba(148,216,255,0.15)]',
    parlayCardStyle: 'bg-[#06122e] border-sky-300/55',
    resultCardStyle: 'bg-[#050f26] border-sky-300/30',
    profileBorderStyle: 'border-sky-300',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-sky-900 to-[#030814]',
    unlockCondition: '750 VouchCoins or Diamond tier',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 750,
    badge: '💠 DIAMOND',
    avatarAnimationClass: 'border-sky-300 shadow-md shadow-sky-300/40',
    particleDemo: ['💎', '❄️', '✨', '🔷'],
    fontFamily: 'font-sans',
    coverBg: 'from-sky-400/25 to-blue-500/20',
    customAIPhrase: '💠 DIAMOND-LEVEL CONFIDENCE ANALYSIS • CLARITY OVER NOISE',
    pageBg: 'bg-[#030814]',
    gridOverlay: 'opacity-10 bg-[radial-gradient(#94D8FF_1px,transparent_1px)] [background-size:20px_20px]',
    borderColor: 'border-sky-300/30',
    accentText: 'text-sky-200'
  },
  {
    id: 'neon-dugout',
    name: 'Neon Dugout',
    category: 'Sport',
    rarity: 'epic',
    description: 'Stadium green and neon lime. Lineup, splits, and matchup data synthesized into a ballpark-night interface.',
    background: 'bg-[#010D04]',
    backgroundPattern: 'stadium',
    cardStyle: 'bg-[#021408]/95 border-green-400/45 shadow-[0_0_28px_rgba(74,222,128,0.18)] backdrop-blur-md',
    borderStyle: 'border-green-400/45',
    glowStyle: 'shadow-green-400/15',
    buttonStyle: 'bg-gradient-to-r from-green-400 to-emerald-600 hover:from-green-300 hover:to-emerald-500 text-slate-950 font-black',
    badgeStyle: 'bg-green-950/80 text-green-400 border-green-800/45',
    sidebarStyle: 'bg-[#010f05] border-r border-green-400/12',
    vouchCardStyle: 'bg-[#04200c] border-green-400/45 shadow-[0_0_12px_rgba(74,222,128,0.12)]',
    parlayCardStyle: 'bg-[#04200c] border-green-400/45',
    resultCardStyle: 'bg-[#031b0a] border-green-400/25',
    profileBorderStyle: 'border-green-400',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-green-950 to-[#010D04]',
    unlockCondition: '400 VouchCoins',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 400,
    badge: '⚾ DUGOUT',
    avatarAnimationClass: 'border-green-400 shadow-md shadow-green-400/40',
    particleDemo: ['⚾', '🎯', '🟢', '⚡'],
    fontFamily: 'font-sans',
    coverBg: 'from-green-500/30 to-emerald-500/20',
    customAIPhrase: '⚾ DUGOUT INTEL • LINEUP AND MATCHUP DATA SYNTHESIZED',
    pageBg: 'bg-[#010D04]',
    gridOverlay: 'opacity-15 bg-[radial-gradient(#4ade80_1.5px,transparent_1.5px)] [background-size:24px_24px]',
    borderColor: 'border-green-400/30',
    accentText: 'text-green-400'
  },
  {
    id: 'ice-ledger',
    name: 'Ice Ledger',
    category: 'Premium',
    rarity: 'epic',
    description: 'Cold arctic blue-white. Emotion-free analysis only — a calm, calculated ledger for tracking every read.',
    background: 'bg-[#020810]',
    backgroundPattern: 'minimal',
    cardStyle: 'bg-[#051529]/90 border-sky-100/40 shadow-[0_0_30px_rgba(186,230,253,0.15)] backdrop-blur-md',
    borderStyle: 'border-sky-100/40',
    glowStyle: 'shadow-sky-200/15',
    buttonStyle: 'bg-gradient-to-r from-sky-200 to-blue-400 hover:from-sky-100 hover:to-blue-300 text-slate-950 font-black',
    badgeStyle: 'bg-slate-900/80 text-sky-200 border-sky-700/40',
    sidebarStyle: 'bg-[#030c18] border-r border-sky-200/12',
    vouchCardStyle: 'bg-[#051829] border-sky-100/40 shadow-[0_0_12px_rgba(186,230,253,0.1)]',
    parlayCardStyle: 'bg-[#051829] border-sky-100/40',
    resultCardStyle: 'bg-[#041424] border-sky-100/25',
    profileBorderStyle: 'border-sky-200',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-slate-800 to-[#020810]',
    unlockCondition: '450 VouchCoins',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 450,
    badge: '❄️ ICE',
    avatarAnimationClass: 'border-sky-200 shadow-md shadow-sky-200/40',
    particleDemo: ['❄️', '🧊', '💠', '⚡'],
    fontFamily: 'font-mono',
    coverBg: 'from-sky-300/20 to-blue-400/20',
    customAIPhrase: '❄️ ICE LEDGER • COLD, CALCULATED • EMOTION-FREE ANALYSIS',
    pageBg: 'bg-[#020810]',
    gridOverlay: 'opacity-8 bg-[radial-gradient(#bae6fd_1px,transparent_1px)] [background-size:20px_20px]',
    borderColor: 'border-sky-100/25',
    accentText: 'text-sky-200'
  },
  {
    id: 'black-gold-vip',
    name: 'Black Gold VIP',
    category: 'Premium',
    rarity: 'legendary',
    description: 'Pure black and gold luxury. Reserved for VIP members — maximum-confidence signals presented with prestige.',
    background: 'bg-[#040200]',
    backgroundPattern: 'glass',
    cardStyle: 'bg-[#080500]/95 border-[#D4AF37]/55 shadow-[0_0_48px_rgba(212,175,55,0.3)] backdrop-blur-md',
    borderStyle: 'border-[#D4AF37]/55',
    glowStyle: 'shadow-[#D4AF37]/25',
    buttonStyle: 'bg-gradient-to-r from-[#D4AF37] to-[#B8960C] hover:from-[#FACC15] hover:to-[#D4AF37] text-slate-950 font-black',
    badgeStyle: 'bg-yellow-950/80 text-[#D4AF37] border-yellow-800/50',
    sidebarStyle: 'bg-[#040200]/97 border-r border-[#D4AF37]/15',
    vouchCardStyle: 'bg-[#0e0800] border-[#D4AF37]/55 shadow-[0_0_14px_rgba(212,175,55,0.18)]',
    parlayCardStyle: 'bg-[#0e0800] border-[#D4AF37]/55',
    resultCardStyle: 'bg-[#0b0600] border-[#D4AF37]/30',
    profileBorderStyle: 'border-[#D4AF37]',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-yellow-950 to-[#040200]',
    unlockCondition: '1000 VouchCoins or Founder status',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 1000,
    badge: '👑 VIP',
    avatarAnimationClass: 'border-[#D4AF37] animate-pulse shadow-md shadow-[#D4AF37]/50',
    particleDemo: ['👑', '💰', '✨', '🏆'],
    fontFamily: 'font-sans',
    coverBg: 'from-[#D4AF37]/30 to-yellow-600/20',
    customAIPhrase: '👑 VIP BLACK GOLD • MAXIMUM-CONFIDENCE SIGNALS ONLY',
    pageBg: 'bg-[#040200]',
    gridOverlay: 'opacity-12 bg-[radial-gradient(#D4AF37_1px,transparent_1px)] [background-size:22px_22px]',
    borderColor: 'border-[#D4AF37]/30',
    accentText: 'text-[#D4AF37]'
  },
  {
    id: 'hr-hunter-mode',
    name: 'HR Hunter Mode',
    category: 'Sport',
    rarity: 'epic',
    description: 'Deep red and fire orange. Scanning ballpark factors, pull-side ISO, and wind to surface power spots.',
    background: 'bg-[#0D0200]',
    backgroundPattern: 'stadium',
    cardStyle: 'bg-[#140400]/95 border-red-500/45 shadow-[0_0_28px_rgba(239,68,68,0.2)] backdrop-blur-md',
    borderStyle: 'border-red-500/45',
    glowStyle: 'shadow-red-500/15',
    buttonStyle: 'bg-gradient-to-r from-red-500 to-orange-500 hover:from-red-400 hover:to-orange-400 text-slate-950 font-black',
    badgeStyle: 'bg-red-950/80 text-red-400 border-red-800/45',
    sidebarStyle: 'bg-[#0d0200] border-r border-red-500/12',
    vouchCardStyle: 'bg-[#1a0400] border-red-500/45 shadow-[0_0_12px_rgba(239,68,68,0.12)]',
    parlayCardStyle: 'bg-[#1a0400] border-red-500/45',
    resultCardStyle: 'bg-[#150300] border-red-500/25',
    profileBorderStyle: 'border-red-500',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-red-950 to-[#0D0200]',
    unlockCondition: '350 VouchCoins',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 350,
    badge: '🔥 HUNTER',
    avatarAnimationClass: 'border-red-500 animate-pulse shadow-md shadow-red-500/50',
    particleDemo: ['⚾', '🔥', '🎯', '💥'],
    fontFamily: 'font-sans',
    coverBg: 'from-red-600/30 to-orange-500/20',
    customAIPhrase: '🔥 HR HUNTER ACTIVE • SCANNING PARK FACTORS AND PULL-SIDE ISO',
    pageBg: 'bg-[#0D0200]',
    gridOverlay: 'opacity-12 bg-[radial-gradient(#ef4444_1.5px,transparent_1.5px)] [background-size:24px_24px]',
    borderColor: 'border-red-500/30',
    accentText: 'text-red-400'
  },
  {
    id: 'risk-room',
    name: 'Risk Room',
    category: 'Premium',
    rarity: 'epic',
    description: 'Warning amber on dark. Built to expose hidden variance, correlation, and capper bias before you commit.',
    background: 'bg-[#08050A]',
    backgroundPattern: 'grid',
    cardStyle: 'bg-[#0e0812]/95 border-yellow-400/50 shadow-[0_0_36px_rgba(251,191,36,0.2)] backdrop-blur-md',
    borderStyle: 'border-yellow-400/50',
    glowStyle: 'shadow-yellow-400/15',
    buttonStyle: 'bg-gradient-to-r from-yellow-400 to-amber-600 hover:from-yellow-300 hover:to-amber-500 text-slate-950 font-black',
    badgeStyle: 'bg-yellow-950/80 text-yellow-400 border-yellow-800/45',
    sidebarStyle: 'bg-[#08050a] border-r border-yellow-400/12',
    vouchCardStyle: 'bg-[#120e00] border-yellow-400/50 shadow-[0_0_12px_rgba(251,191,36,0.12)]',
    parlayCardStyle: 'bg-[#120e00] border-yellow-400/50',
    resultCardStyle: 'bg-[#0e0b00] border-yellow-400/25',
    profileBorderStyle: 'border-yellow-400',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-yellow-950 to-[#08050A]',
    unlockCondition: '600 VouchCoins',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 600,
    badge: '⚠️ RISK ROOM',
    avatarAnimationClass: 'border-yellow-400 shadow-md shadow-yellow-400/40',
    particleDemo: ['⚠️', '📊', '🎲', '💡'],
    fontFamily: 'font-mono',
    coverBg: 'from-yellow-500/25 to-amber-600/20',
    customAIPhrase: '⚠️ RISK ROOM • EXPOSING HIDDEN VARIANCE AND CAPPER BIAS',
    pageBg: 'bg-[#08050A]',
    gridOverlay: 'opacity-10 bg-[radial-gradient(#fbbf24_1px,transparent_1px)] [background-size:20px_20px]',
    borderColor: 'border-yellow-400/30',
    accentText: 'text-yellow-400'
  },
  {
    id: 'galactic-trust-v2',
    name: 'Galactic Trust V2',
    category: 'Trust',
    rarity: 'verified',
    description: 'Black and deep-space gold. An immutable audit-trail aesthetic for verified-record cappers who lead with proof.',
    background: 'bg-[#020510]',
    backgroundPattern: 'grid',
    cardStyle: 'bg-[#040614]/95 border-[#FFE81F]/55 shadow-[0_0_44px_rgba(255,232,31,0.25)] backdrop-blur-md',
    borderStyle: 'border-[#FFE81F]/55',
    glowStyle: 'shadow-[#FFE81F]/20',
    buttonStyle: 'bg-gradient-to-r from-[#FFE81F] to-yellow-600 hover:from-yellow-300 hover:to-amber-500 text-slate-950 font-black',
    badgeStyle: 'bg-yellow-950/80 text-[#FFE81F] border-yellow-800/45',
    sidebarStyle: 'bg-[#020510]/97 border-r border-[#FFE81F]/12',
    vouchCardStyle: 'bg-[#070814] border-[#FFE81F]/55 shadow-[0_0_14px_rgba(255,232,31,0.15)]',
    parlayCardStyle: 'bg-[#070814] border-[#FFE81F]/55',
    resultCardStyle: 'bg-[#050610] border-[#FFE81F]/30',
    profileBorderStyle: 'border-[#FFE81F]',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-yellow-950 to-[#020510]',
    unlockCondition: '800 VouchCoins or Verified Trust badge',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 800,
    badge: '🛡️ GALACTIC V2',
    avatarAnimationClass: 'border-[#FFE81F] animate-pulse shadow-md shadow-[#FFE81F]/40',
    particleDemo: ['🛡️', '✨', '🛰️', '💫'],
    fontFamily: 'font-mono',
    coverBg: 'from-[#FFE81F]/25 to-amber-600/20',
    customAIPhrase: '🛡️ IMMUTABLE AUDIT TRAIL ACTIVE • GALACTIC LEDGER V2 ONLINE',
    pageBg: 'bg-[#020510]',
    gridOverlay: 'opacity-15 bg-[radial-gradient(#FFE81F_1px,transparent_1px)] [background-size:24px_24px]',
    borderColor: 'border-[#FFE81F]/30',
    accentText: 'text-[#FFE81F]'
  },
  {
    id: 'founder-mode',
    name: 'Founder Mode',
    category: 'Premium',
    rarity: 'founder',
    description: 'Ultra-dark with electric violet. Exclusive to original members — full system access, founder identity engaged.',
    background: 'bg-[#030005]',
    backgroundPattern: 'glass',
    cardStyle: 'bg-[#06000a]/97 border-violet-400/60 shadow-[0_0_60px_rgba(167,139,250,0.35)] backdrop-blur-md',
    borderStyle: 'border-violet-400/60',
    glowStyle: 'shadow-violet-400/25',
    buttonStyle: 'bg-gradient-to-r from-violet-400 to-purple-700 hover:from-violet-300 hover:to-purple-600 text-slate-950 font-black',
    badgeStyle: 'bg-violet-950/80 text-violet-300 border-violet-700/55',
    sidebarStyle: 'bg-[#030005]/97 border-r border-violet-400/15',
    vouchCardStyle: 'bg-[#0a0020] border-violet-400/60 shadow-[0_0_16px_rgba(167,139,250,0.2)]',
    parlayCardStyle: 'bg-[#0a0020] border-violet-400/60',
    resultCardStyle: 'bg-[#08001a] border-violet-400/30',
    profileBorderStyle: 'border-violet-400',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-violet-950 to-[#030005]',
    unlockCondition: 'Founder badge required — exclusive to original members',
    isPremium: true,
    isEarned: true,
    isSeasonal: false,
    cost: 9999,
    badge: '🚀 FOUNDER',
    avatarAnimationClass: 'border-violet-400 animate-pulse shadow-lg shadow-violet-400/50',
    particleDemo: ['🚀', '⚡', '🌌', '✨'],
    fontFamily: 'font-sans',
    coverBg: 'from-violet-500/30 to-purple-700/20',
    customAIPhrase: '🚀 FOUNDER MODE • YOU BUILT THIS • FULL SYSTEM ACCESS ENGAGED',
    pageBg: 'bg-[#030005]',
    gridOverlay: 'opacity-12 bg-[radial-gradient(#a78bfa_1px,transparent_1px)] [background-size:22px_22px]',
    borderColor: 'border-violet-400/30',
    accentText: 'text-violet-300'
  },
  {
    id: 'cyber-blue',
    name: 'Cyber Blue',
    category: 'Core',
    rarity: 'common',
    description: 'Default VouchEdge experience. Deep navy base with electric cyan nodes, zig-zag data flows, and sleek high-contrast sports analytics overlays.',
    background: 'bg-[#060a13]',
    backgroundPattern: 'grid',
    cardStyle: 'bg-[#0f1524]/90 border-cyan-500/30 shadow-[0_0_15px_rgba(6,182,212,0.15)] backdrop-blur-md',
    borderStyle: 'border-cyan-500/30',
    glowStyle: 'shadow-cyan-500/10',
    buttonStyle: 'bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 font-black',
    badgeStyle: 'bg-cyan-950/80 text-cyan-400 border-cyan-800/45',
    sidebarStyle: 'bg-[#090d16]/95 border-r border-cyan-500/10',
    vouchCardStyle: 'bg-[#121a2f] border-cyan-500/30 shadow-[0_0_10px_rgba(6,182,212,0.1)]',
    parlayCardStyle: 'bg-[#121a2f] border-cyan-500/30',
    resultCardStyle: 'bg-[#111827] border-cyan-500/20',
    profileBorderStyle: 'border-cyan-500',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-cyan-900 to-[#060a13]',
    unlockCondition: 'Unrestricted baseline standard theme',
    isPremium: false,
    isEarned: false,
    isSeasonal: false,
    cost: 0,
    badge: '⚡ CYBER',
    avatarAnimationClass: 'border-cyan-500 shadow-md shadow-cyan-500/30',
    particleDemo: ['⚡', '💎', '📈', '🔵'],
    fontFamily: 'font-sans',
    coverBg: 'from-cyan-500/20 to-blue-600/20',
    customAIPhrase: '⚡ CYBER INTELLIGENCE SYSTEM ENGAGED • ALL PROP RATINGS LIVE',
    pageBg: 'bg-[#060a13]',
    gridOverlay: 'opacity-10 bg-[radial-gradient(#06b6d4_1px,transparent_1px)] [background-size:20px_20px]',
    borderColor: 'border-cyan-500/20',
    accentText: 'text-cyan-400'
  },
  {
    id: 'neon-court',
    name: 'Neon Court',
    category: 'Sport',
    rarity: 'rare',
    description: 'Immersive hardwood simulation optimized for NBA props. Deep black with basketball-orange lanes and neon backboard vectors.',
    background: 'bg-[#090705]',
    backgroundPattern: 'court',
    cardStyle: 'bg-[#140e0a]/95 border-orange-500/40 shadow-[0_0_20px_rgba(249,115,22,0.15)] backdrop-blur-md',
    borderStyle: 'border-orange-500/40',
    glowStyle: 'shadow-orange-500/15',
    buttonStyle: 'bg-gradient-to-r from-orange-500 to-amber-600 hover:from-orange-400 hover:to-amber-500 text-slate-950 font-black',
    badgeStyle: 'bg-orange-950/80 text-orange-400 border-orange-800/45',
    sidebarStyle: 'bg-[#0e0a07] border-r border-orange-500/10',
    vouchCardStyle: 'bg-[#18110b] border-orange-500/40 shadow-[0_0_12px_rgba(249,115,22,0.12)]',
    parlayCardStyle: 'bg-[#18110b] border-orange-500/40',
    resultCardStyle: 'bg-[#16100a] border-orange-500/25',
    profileBorderStyle: 'border-orange-500',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-orange-950 to-[#090705]',
    unlockCondition: 'Unlocks after saving your first verified NBA Vouch',
    isPremium: false,
    isEarned: true,
    isSeasonal: false,
    cost: 150,
    badge: '🏀 COURT',
    avatarAnimationClass: 'border-orange-500 animate-pulse shadow-md shadow-orange-500/50',
    particleDemo: ['🏀', '⚡', '🔥', '👟'],
    fontFamily: 'font-sans',
    coverBg: 'from-orange-600/30 to-amber-500/20',
    customAIPhrase: '🏀 COURT VISION ACTIVE • HARDWOOD PROPS SYNCHRONIZING',
    pageBg: 'bg-[#090705]',
    gridOverlay: 'opacity-15 bg-[radial-gradient(#f97316_1.5px,transparent_1.5px)] [background-size:24px_24px]',
    borderColor: 'border-orange-500/30',
    accentText: 'text-orange-400'
  },
  {
    id: 'diamond-glow',
    name: 'Diamond Glow',
    category: 'Sport',
    rarity: 'rare',
    description: 'Immersive dark ballpark feeling under bright stadium floodlights. Rich emerald turf gradients and cyan diamond geometries.',
    background: 'bg-[#020d09]',
    backgroundPattern: 'stadium',
    cardStyle: 'bg-[#041a12]/95 border-emerald-500/40 shadow-[0_0_20px_rgba(16,185,129,0.15)] backdrop-blur-md',
    borderStyle: 'border-emerald-500/45',
    glowStyle: 'shadow-emerald-500/15',
    buttonStyle: 'bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-400 hover:to-teal-500 text-slate-950 font-black',
    badgeStyle: 'bg-emerald-950/80 text-emerald-400 border-emerald-800/45',
    sidebarStyle: 'bg-[#02130e] border-r border-emerald-500/10',
    vouchCardStyle: 'bg-[#05261b] border-emerald-500/40 shadow-[0_0_12px_rgba(16,185,129,0.12)]',
    parlayCardStyle: 'bg-[#05261b] border-emerald-500/40',
    resultCardStyle: 'bg-[#042016] border-emerald-500/25',
    profileBorderStyle: 'border-emerald-500',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-emerald-950 to-[#020d09]',
    unlockCondition: 'Unlocks after saving your first verified MLB Vouch',
    isPremium: false,
    isEarned: true,
    isSeasonal: false,
    cost: 150,
    badge: '⚾ BALLPARK',
    avatarAnimationClass: 'border-emerald-500 animate-bounce shadow-md shadow-emerald-500/50',
    particleDemo: ['⚾', '🧢', '🏟️', '🟢'],
    fontFamily: 'font-sans',
    coverBg: 'from-emerald-600/30 to-teal-500/20',
    customAIPhrase: '⚾ STADIUM AUDITING ENGAGED • RADAR VELOCITIES ONLINE',
    pageBg: 'bg-[#020d09]',
    gridOverlay: 'opacity-15 bg-[radial-gradient(#10b981_1.5px,transparent_1.5px)] [background-size:28px_28px]',
    borderColor: 'border-emerald-500/30',
    accentText: 'text-emerald-400'
  },
  {
    id: 'dark-shark',
    name: 'Dark Shark',
    category: 'Flex',
    rarity: 'epic',
    description: 'Aggressive, sharp-edged theme for high-stake parlay climbers. Darkest obsidian textures with intense neon crimson borders.',
    background: 'bg-[#030305]',
    backgroundPattern: 'minimal',
    cardStyle: 'bg-black border-rose-600/50 shadow-[0_0_25px_rgba(225,29,72,0.2)] rounded-none border-2',
    borderStyle: 'border-rose-600/55',
    glowStyle: 'shadow-rose-600/20',
    buttonStyle: 'bg-gradient-to-r from-rose-600 to-red-700 hover:from-rose-500 hover:to-red-650 text-white font-black uppercase tracking-wider rounded-none',
    badgeStyle: 'bg-rose-950/90 text-rose-400 border-rose-800/60 font-mono font-bold',
    sidebarStyle: 'bg-black border-r-2 border-rose-600/20',
    vouchCardStyle: 'bg-slate-950 border-rose-600/50 shadow-[0_0_12px_rgba(225,29,72,0.15)] rounded-none border',
    parlayCardStyle: 'bg-slate-950 border-rose-600/50 rounded-none border',
    resultCardStyle: 'bg-black border-rose-600/30 rounded-none border',
    profileBorderStyle: 'border-rose-600 rounded-none border-2',
    animationStyle: 'transition-all duration-150',
    shareCardStyle: 'from-red-950 to-black',
    unlockCondition: 'Available as a premium subscription unlock or rare achievement reward',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 300,
    badge: '🦈 SHARK',
    avatarAnimationClass: 'border-rose-500 ring-2 ring-red-650 animate-pulse rounded-none',
    particleDemo: ['🦈', '🩸', '💀', '💸'],
    fontFamily: 'font-mono',
    coverBg: 'from-rose-600/30 to-red-950/40',
    customAIPhrase: '💀 SHARK ALGORITHM ENGAGED • HIGH RISK / MAXIMUM UNITS LOADED',
    pageBg: 'bg-[#030305]',
    gridOverlay: 'opacity-25 bg-[linear-gradient(rgba(225,29,72,0.06)_1px,transparent_1px),linear-gradient(90deg,rgba(225,29,72,0.06)_1px,transparent_1px)] [background-size:24px_24px]',
    borderColor: 'border-rose-600/30',
    accentText: 'text-rose-500 font-bold'
  },
  {
    id: 'proof-mode',
    name: 'Proof Mode',
    category: 'Minimal',
    rarity: 'common',
    description: 'Ultra-clean capper theme. Pure stark black-and-white layouts focused exclusively on track records, verified win percentages, and cold stats.',
    background: 'bg-[#0c0d0f]',
    backgroundPattern: 'minimal',
    cardStyle: 'bg-[#131518] border-slate-700 shadow-md',
    borderStyle: 'border-slate-600',
    glowStyle: 'shadow-none',
    buttonStyle: 'bg-slate-100 hover:bg-slate-200 text-slate-950 font-extrabold rounded-md',
    badgeStyle: 'bg-slate-800 text-slate-200 border-slate-600 font-mono text-[10px]',
    sidebarStyle: 'bg-[#0b0c0e] border-r border-slate-800',
    vouchCardStyle: 'bg-[#15171b] border-slate-700 shadow-none',
    parlayCardStyle: 'bg-[#15171b] border-slate-700 shadow-none',
    resultCardStyle: 'bg-[#101214] border-slate-800',
    profileBorderStyle: 'border-slate-400',
    animationStyle: 'transition-none',
    shareCardStyle: 'from-slate-900 to-black',
    unlockCondition: 'Unlocks for all certified proof compilers automatically',
    isPremium: false,
    isEarned: false,
    isSeasonal: false,
    cost: 50,
    badge: '🛡️ PROOF',
    avatarAnimationClass: 'border-slate-350 scale-95 opacity-90',
    particleDemo: ['🔍', '📊', '✓', '🗄️'],
    fontFamily: 'font-sans',
    coverBg: 'from-slate-800/40 to-slate-950/40',
    customAIPhrase: '🔍 COGNITIVE AUDITING MODE: ZERO COSMETIC OVERHEAD',
    pageBg: 'bg-[#0c0d0f]',
    gridOverlay: 'opacity-5 bg-[radial-gradient(#ffffff_1px,transparent_1px)] [background-size:16px_16px]',
    borderColor: 'border-slate-800',
    accentText: 'text-slate-200'
  },
  {
    id: 'gold-standard',
    name: 'Gold Standard',
    category: 'Premium',
    rarity: 'legendary',
    description: 'The absolute pinnacle of premium trust status. Heavy golden-liquid overlays, polished dark marble card textures, and capper crown tags.',
    background: 'bg-[#070502]',
    backgroundPattern: 'stadium',
    cardStyle: 'bg-gradient-to-br from-[#1c1408] via-[#0e0a04] to-black border-yellow-500/50 shadow-[0_0_30px_rgba(234,179,8,0.2)]',
    borderStyle: 'border-yellow-500/50',
    glowStyle: 'shadow-yellow-500/20',
    buttonStyle: 'bg-gradient-to-r from-yellow-500 via-amber-400 to-yellow-600 hover:from-yellow-400 hover:to-yellow-500 text-slate-950 font-black tracking-wide',
    badgeStyle: 'bg-yellow-950 text-yellow-400 border-yellow-700/60',
    sidebarStyle: 'bg-[#0e0904] border-r border-yellow-500/15',
    vouchCardStyle: 'bg-gradient-to-tr from-[#1f1609] to-[#0a0703] border-yellow-500/50 shadow-[0_0_15px_rgba(234,179,8,0.12)]',
    parlayCardStyle: 'bg-[#1f1609] border-yellow-500/50',
    resultCardStyle: 'bg-black border-yellow-500/30',
    profileBorderStyle: 'border-yellow-500 ring-2 ring-yellow-400/30',
    animationStyle: 'transition-all duration-500',
    shareCardStyle: 'from-yellow-950 to-black',
    unlockCondition: 'Earned with a Trust Score of 85+ or through Premium subscriber store credit licensing',
    isPremium: true,
    isEarned: true,
    isSeasonal: false,
    cost: 500,
    badge: '👑 GOLD',
    avatarAnimationClass: 'border-yellow-400 border-4 shadow-lg shadow-yellow-500/60 scale-105',
    particleDemo: ['👑', '🏆', '🪙', '💰'],
    fontFamily: 'font-sans',
    coverBg: 'from-yellow-600/30 to-amber-600/20',
    customAIPhrase: '👑 GOLDEN GRADER INSTANCE ENGAGED • 100% UNBIASED PROOF OUTCOMES',
    pageBg: 'bg-[#070502]',
    gridOverlay: 'opacity-15 bg-[radial-gradient(#eab308_1px,transparent_1px)] [background-size:24px_24px]',
    borderColor: 'border-yellow-500/20',
    accentText: 'text-yellow-400'
  },
  {
    id: 'ice-glass',
    name: 'Ice Glass',
    category: 'Premium',
    rarity: 'epic',
    description: 'Immaculate translucent layout built on pristine glassmorphism. Shimmering frosted glass panels, winter wind particles, and neon arctic glows.',
    background: 'bg-[#07131a]',
    backgroundPattern: 'glass',
    cardStyle: 'bg-white/5 border-sky-300/35 backdrop-blur-xl shadow-[0_8px_32px_0_rgba(14,165,233,0.15)]',
    borderStyle: 'border-sky-300/30',
    glowStyle: 'shadow-sky-400/10',
    buttonStyle: 'bg-[#0ea5e9] hover:bg-[#38bdf8] text-white font-bold tracking-wide shadow-[0_0_15px_rgba(14,165,233,0.4)]',
    badgeStyle: 'bg-sky-950/50 text-sky-300 border-sky-800/40 backdrop-blur-md',
    sidebarStyle: 'bg-[#030911]/80 border-r border-sky-300/10 backdrop-blur-md',
    vouchCardStyle: 'bg-white/5 border-sky-300/30 backdrop-blur-lg shadow-inner',
    parlayCardStyle: 'bg-white/5 border-sky-300/30 backdrop-blur-lg',
    resultCardStyle: 'bg-white/5 border-sky-300/20 backdrop-blur-lg',
    profileBorderStyle: 'border-sky-300',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-sky-950 to-[#07131a]',
    unlockCondition: 'Unlocks directly for Premium subscription tier owners',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 350,
    badge: '❄️ ARCTIC',
    avatarAnimationClass: 'border-sky-300 shadow-md shadow-sky-400/40 rotate-2',
    particleDemo: ['❄️', '🧊', '🌬️', '💎'],
    fontFamily: 'font-sans',
    coverBg: 'from-sky-500/20 to-indigo-600/10',
    customAIPhrase: '❄️ FROSTED GRADER ARCHIVE ENGAGED • ICE ODDS LOCKED IN',
    pageBg: 'bg-[#07131a]',
    gridOverlay: 'opacity-10 bg-[radial-gradient(#38bdf8_1px,transparent_1px)] [background-size:20px_20px]',
    borderColor: 'border-sky-300/20',
    accentText: 'text-sky-300'
  },
  {
    id: 'redline',
    name: 'Redline',
    category: 'Seasonal',
    rarity: 'rare',
    description: 'High-octane theme mimicking glowing sports scoreboard consoles. Blazing scarlet alarms, intense grid alignment lines, and race-day energy accents.',
    background: 'bg-[#0c0506]',
    backgroundPattern: 'stadium',
    cardStyle: 'bg-[#1a0c0e]/95 border-red-500/40 shadow-[0_0_20px_rgba(239,68,68,0.18)] backdrop-blur-md',
    borderStyle: 'border-red-500/40',
    glowStyle: 'shadow-red-500/15',
    buttonStyle: 'bg-gradient-to-r from-red-600 to-rose-700 hover:from-red-500 hover:to-rose-600 text-white font-extrabold uppercase',
    badgeStyle: 'bg-red-950/80 text-red-400 border-red-900/45',
    sidebarStyle: 'bg-[#12080a] border-r border-red-500/10',
    vouchCardStyle: 'bg-[#221013] border-red-500/40 shadow-[0_0_12px_rgba(239,68,68,0.12)]',
    parlayCardStyle: 'bg-[#221013] border-red-500/40',
    resultCardStyle: 'bg-[#1c0d0f] border-red-500/25',
    profileBorderStyle: 'border-red-500',
    animationStyle: 'transition-all duration-200',
    shareCardStyle: 'from-red-950 to-[#0c0506]',
    unlockCondition: 'Unlocks during peak live-play sporting events or high win streaks',
    isPremium: false,
    isEarned: true,
    isSeasonal: true,
    cost: 200,
    badge: '🚨 ALERT',
    avatarAnimationClass: 'border-red-500 border-2 animate-pulse text-red-400 shadow-md shadow-red-500/40',
    particleDemo: ['🚨', '🔥', '🏎️', '🔴'],
    fontFamily: 'font-sans',
    coverBg: 'from-red-600/30 to-rose-600/20',
    customAIPhrase: '🚨 LIVE REDLINE METRICS LOADING • RAPID RE-TRACKING INSTANCE ACTIVE',
    pageBg: 'bg-[#0c0506]',
    gridOverlay: 'opacity-15 bg-[radial-gradient(#ef4444_1.5px,transparent_1.5px)] [background-size:22px_22px]',
    borderColor: 'border-red-500/30',
    accentText: 'text-red-400'
  },
  
  // Retro arcade series
  {
    id: '4bit-arcade',
    name: '4-Bit Arcade',
    category: 'Retro',
    rarity: 'rare',
    description: 'Impeccable blocky pixel styling that turns VouchEdge into a classic 80s arcade. Scanline monitors, retro neon pixel blocks, and neon buttons.',
    background: 'bg-[#050508]',
    backgroundPattern: 'arcade',
    cardStyle: 'bg-[#0f0f18] border-purple-500 border-4 shadow-[0_0_15px_rgba(168,85,247,0.3)] font-mono text-xs rounded-none',
    borderStyle: 'border-purple-500 border-4',
    glowStyle: 'shadow-purple-500/20',
    buttonStyle: 'bg-[#a855f7] border-[#c084fc] border-2 hover:bg-[#9333ea] text-white font-mono font-bold uppercase rounded-none',
    badgeStyle: 'bg-[#3b0764] text-purple-300 border-purple-500 border rounded-none font-mono text-[9px] uppercase',
    sidebarStyle: 'bg-[#07070d] border-r-4 border-purple-500',
    vouchCardStyle: 'bg-[#131322] border-purple-500 border-2 rounded-none shadow-none',
    parlayCardStyle: 'bg-[#131322] border-purple-500 border-2 rounded-none',
    resultCardStyle: 'bg-[#0c0c14] border-purple-500 border rounded-none',
    profileBorderStyle: 'border-purple-500 border-4 rounded-none',
    animationStyle: 'transition-all duration-200',
    shareCardStyle: 'from-purple-950 to-[#050508]',
    unlockCondition: 'Unrestricted entry-level Retro Theme',
    isPremium: false,
    isEarned: false,
    isSeasonal: false,
    cost: 100,
    badge: '👾 PIXEL',
    avatarAnimationClass: 'border-purple-500 border-4 shadow-lg rounded-none',
    particleDemo: ['👾', '🎮', '⭐️', '🪙'],
    fontFamily: 'font-mono',
    coverBg: 'from-purple-600/40 to-indigo-900/30',
    customAIPhrase: '👾 INSERT COIN • RETRO GRADER RUNNING COMPILING DEEP METRICS',
    pageBg: 'bg-[#050508]',
    gridOverlay: 'opacity-15 bg-[linear-gradient(rgba(168,85,247,0.1)_1px,transparent_1px)] [background-size:100%_6px]',
    borderColor: 'border-purple-500/30',
    accentText: 'text-purple-400 font-mono'
  },
  {
    id: '4bit-court',
    name: '4-Bit Court',
    category: 'Retro',
    rarity: 'rare',
    description: 'Brings retro arcade sports titles to life. Interactive orange-brown pixel lines representing basketball court lanes under 4-bit scoring widgets.',
    background: 'bg-[#0a0604]',
    backgroundPattern: 'arcade',
    cardStyle: 'bg-[#140b07] border-orange-500 border-4 shadow-[0_0_15px_rgba(249,115,22,0.3)] font-mono text-xs rounded-none',
    borderStyle: 'border-orange-500 border-4',
    glowStyle: 'shadow-orange-500/20',
    buttonStyle: 'bg-[#f97316] border-[#fb923c] border-2 hover:bg-[#ea580c] text-slate-950 font-mono font-black uppercase rounded-none',
    badgeStyle: 'bg-[#7c2d12] text-orange-200 border-orange-500 border rounded-none font-mono text-[9px] uppercase',
    sidebarStyle: 'bg-[#0d0704] border-r-4 border-orange-500',
    vouchCardStyle: 'bg-[#1c100a] border-orange-500 border-2 rounded-none shadow-none',
    parlayCardStyle: 'bg-[#1c100a] border-orange-500 border-2 rounded-none',
    resultCardStyle: 'bg-[#120a06] border-orange-500 border rounded-none',
    profileBorderStyle: 'border-orange-500 border-4 rounded-none',
    animationStyle: 'transition-all duration-200',
    shareCardStyle: 'from-orange-950 to-[#0a0604]',
    unlockCondition: 'Unlocks after 5 successful verified NBA basketball slips recorded',
    isPremium: false,
    isEarned: true,
    isSeasonal: false,
    cost: 250,
    badge: '🏀 ARCADE_HOOPS',
    avatarAnimationClass: 'border-orange-500 border-4 shadow-lg rounded-none',
    particleDemo: ['🏀', '👟', '⭐️', '📺'],
    fontFamily: 'font-mono',
    coverBg: 'from-orange-600/40 to-amber-700/30',
    customAIPhrase: '🏀 HOOPS 4-BIT ENGINE ACTIVE • CHIP-TUNE DRIVERS ON',
    pageBg: 'bg-[#0a0604]',
    gridOverlay: 'opacity-15 bg-[linear-gradient(rgba(249,115,22,0.1)_1px,transparent_1px)] [background-size:100%_6px]',
    borderColor: 'border-orange-500/30',
    accentText: 'text-orange-400 font-mono'
  },
  {
    id: '4bit-diamond',
    name: '4-Bit Diamond',
    category: 'Retro',
    rarity: 'rare',
    description: 'Pixel baseball retro theme inspired by classic console baseball games. Ballpark scoreboard cards and green grid lines.',
    background: 'bg-[#030a06]',
    backgroundPattern: 'arcade',
    cardStyle: 'bg-[#051a0e] border-emerald-500 border-4 shadow-[0_0_15px_rgba(16,185,129,0.3)] font-mono text-xs rounded-none',
    borderStyle: 'border-emerald-500 border-4',
    glowStyle: 'shadow-emerald-500/20',
    buttonStyle: 'bg-[#10b981] border-[#34d399] border-2 hover:bg-[#059669] text-slate-950 font-mono font-black uppercase rounded-none',
    badgeStyle: 'bg-[#064e3b] text-emerald-200 border-emerald-500 border rounded-none font-mono text-[9px] uppercase',
    sidebarStyle: 'bg-[#030e07] border-r-4 border-emerald-500',
    vouchCardStyle: 'bg-[#082816] border-emerald-500 border-2 rounded-none shadow-none',
    parlayCardStyle: 'bg-[#082816] border-emerald-500 border-2 rounded-none',
    resultCardStyle: 'bg-[#04160c] border-emerald-500 border rounded-none',
    profileBorderStyle: 'border-emerald-500 border-4 rounded-none',
    animationStyle: 'transition-all duration-200',
    shareCardStyle: 'from-emerald-950 to-[#030a06]',
    unlockCondition: 'Unlocks after 5 successful verified MLB baseball slips recorded',
    isPremium: false,
    isEarned: true,
    isSeasonal: false,
    cost: 250,
    badge: '⚾ ARCADE_SLUGGER',
    avatarAnimationClass: 'border-emerald-500 border-4 shadow-lg rounded-none',
    particleDemo: ['⚾', '🧢', '⭐', '🏟️'],
    fontFamily: 'font-mono',
    coverBg: 'from-emerald-600/40 to-teal-800/30',
    customAIPhrase: '⚾ BASEBALL 4-BIT SCOREBOARD RUNNING • CHIP TUNES READY',
    pageBg: 'bg-[#030a06]',
    gridOverlay: 'opacity-15 bg-[linear-gradient(rgba(16,185,129,0.1)_1px,transparent_1px)] [background-size:100%_6px]',
    borderColor: 'border-emerald-500/30',
    accentText: 'text-emerald-400 font-mono'
  },
  {
    id: '4bit-cyber',
    name: '4-Bit Cyber',
    category: 'Retro',
    rarity: 'epic',
    description: 'The ultimate hybrid of neon cyber-blue grids and classic 8-bit chunky outline architecture. Custom animated neon scanlines.',
    background: 'bg-[#03050a]',
    backgroundPattern: 'pixel-zig',
    cardStyle: 'bg-[#060a16] border-cyan-400 border-4 shadow-[0_0_20px_rgba(34,211,238,0.35)] font-mono text-xs rounded-none',
    borderStyle: 'border-cyan-400 border-4',
    glowStyle: 'shadow-cyan-400/20',
    buttonStyle: 'bg-[#22d3ee] border-[#06b6d4] border-2 hover:bg-[#0891b2] text-slate-950 font-mono font-black uppercase rounded-none',
    badgeStyle: 'bg-[#083344] text-cyan-200 border-cyan-400 border rounded-none font-mono text-[9px] uppercase',
    sidebarStyle: 'bg-[#020409] border-r-4 border-cyan-400',
    vouchCardStyle: 'bg-[#0a1124] border-cyan-400 border-2 rounded-none shadow-none',
    parlayCardStyle: 'bg-[#0a1124] border-cyan-400 border-2 rounded-none',
    resultCardStyle: 'bg-[#050914] border-cyan-400 border rounded-none',
    profileBorderStyle: 'border-cyan-400 border-4 rounded-none',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-cyan-950 to-[#03050a]',
    unlockCondition: 'Available through premium theme store locker license upgrade',
    isPremium: true,
    isEarned: false,
    isSeasonal: false,
    cost: 400,
    badge: '📟 CYBER_8BIT',
    avatarAnimationClass: 'border-cyan-400 border-4 shadow-lg rounded-none',
    particleDemo: ['⚡', '💎', '🔵', '📟'],
    fontFamily: 'font-mono',
    coverBg: 'from-cyan-600/40 to-blue-900/30',
    customAIPhrase: '📟 CYBER-PIXEL DEEP CODE ENGAGED • CHIP-TUNE ENABLER ON',
    pageBg: 'bg-[#03050a]',
    gridOverlay: 'opacity-15 bg-[linear-gradient(rgba(34,211,238,0.1)_1px,transparent_1px)] [background-size:100%_6px]',
    borderColor: 'border-cyan-400/30',
    accentText: 'text-cyan-400 font-mono'
  },
  {
    id: '8bit-champion',
    name: '8-Bit Champion',
    category: 'Trust',
    rarity: 'legendary',
    description: 'Prestige retro capper theme. Blends royal championship gold pixel outlines with sparkling retro stars and animated trophy indicators.',
    background: 'bg-[#080602]',
    backgroundPattern: 'pixel-zig',
    cardStyle: 'bg-[#140e04] border-yellow-500 border-4 shadow-[0_0_22px_rgba(234,179,8,0.4)] font-mono text-xs rounded-none',
    borderStyle: 'border-yellow-500 border-4',
    glowStyle: 'shadow-yellow-500/25',
    buttonStyle: 'bg-[#eab308] border-[#fef08a] border-2 hover:bg-[#ca8a04] text-slate-950 font-mono font-black uppercase rounded-none',
    badgeStyle: 'bg-[#451a03] text-yellow-200 border-yellow-500 border rounded-none font-mono text-[9px] uppercase',
    sidebarStyle: 'bg-[#0a0702] border-r-4 border-yellow-500',
    vouchCardStyle: 'bg-[#1d1406] border-yellow-500 border-2 rounded-none shadow-none',
    parlayCardStyle: 'bg-[#1d1406] border-yellow-500 border-2 rounded-none',
    resultCardStyle: 'bg-[#100a03] border-yellow-500 border rounded-none',
    profileBorderStyle: 'border-yellow-500 border-4 rounded-none',
    animationStyle: 'transition-all duration-500',
    shareCardStyle: 'from-yellow-950 to-[#080602]',
    unlockCondition: 'Unlocks only for legendary leader board achievements or an active 5-pick win streak',
    isPremium: false,
    isEarned: true,
    isSeasonal: false,
    cost: 600,
    badge: '👑 CHAMP_8BIT',
    avatarAnimationClass: 'border-yellow-500 border-4 shadow-xl rounded-none animate-bounce',
    particleDemo: ['👑', '🏆', '⭐', '🪙'],
    fontFamily: 'font-mono',
    coverBg: 'from-yellow-600/40 to-amber-700/30',
    customAIPhrase: '🏆 8-BIT CHAMPION CHIP UNLOCKED • LEGENDARY WIN STREAK ACTIVE',
    pageBg: 'bg-[#080602]',
    gridOverlay: 'opacity-15 bg-[linear-gradient(rgba(234,179,8,0.1)_1px,transparent_1px)] [background-size:100%_6px]',
    borderColor: 'border-yellow-500/30',
    accentText: 'text-yellow-400 font-mono'
  },

  // ============ FREE BETA THEMES ============
  {
    id: 'beta-cyber-blue',
    name: 'Beta Cyber Blue',
    category: 'Core',
    rarity: 'common',
    description: 'VouchEdge core look — dark navy with electric cyan glow. Clean sports analytics feel. Free for all beta users.',
    background: 'bg-[#050B18]',
    backgroundPattern: 'grid',
    cardStyle: 'bg-[#0b1224]/90 border-[#00B7FF]/35 shadow-[0_0_28px_rgba(0,183,255,0.18)] backdrop-blur-md',
    borderStyle: 'border-[#00B7FF]/35',
    glowStyle: 'shadow-[#00B7FF]/15',
    buttonStyle: 'bg-gradient-to-r from-[#00B7FF] to-[#2563EB] hover:from-[#22D3EE] hover:to-[#00B7FF] text-slate-950 font-black',
    badgeStyle: 'bg-[#00B7FF]/10 text-[#00B7FF] border-[#00B7FF]/35',
    sidebarStyle: 'bg-[#050b18]/95 border-r border-[#00B7FF]/12',
    vouchCardStyle: 'bg-[#0b1224] border-[#00B7FF]/35 shadow-[0_0_12px_rgba(0,183,255,0.12)]',
    parlayCardStyle: 'bg-[#0b1224] border-[#00B7FF]/35',
    resultCardStyle: 'bg-[#0a1120] border-[#00B7FF]/25',
    profileBorderStyle: 'border-[#00B7FF]',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-[#062033] to-[#050B18]',
    unlockCondition: 'Free — available to all beta users',
    isPremium: false,
    isEarned: false,
    isSeasonal: false,
    cost: 0,
    badge: '⚡ BETA CYBER',
    avatarAnimationClass: 'border-[#00B7FF] shadow-md shadow-[#00B7FF]/40',
    particleDemo: ['⚡', '🔵', '✨', '🎯'],
    fontFamily: 'font-sans',
    coverBg: 'from-[#00B7FF]/25 to-[#2563EB]/20',
    customAIPhrase: '⚡ BETA CYBER BLUE · VOUCHEDGE CORE EXPERIENCE',
    pageBg: 'bg-[#050B18]',
    gridOverlay: 'opacity-10 bg-[radial-gradient(#00B7FF_1px,transparent_1px)] [background-size:20px_20px]',
    borderColor: 'border-[#00B7FF]/25',
    accentText: 'text-[#00B7FF]'
  },
  {
    id: 'beta-gold-proof',
    name: 'Beta Gold Proof',
    category: 'Premium',
    rarity: 'legendary',
    description: 'Black and gold — premium capper club, verified proof energy. Luxury proof identity. Free for all beta users.',
    background: 'bg-[#040200]',
    backgroundPattern: 'glass',
    cardStyle: 'bg-[#080500]/95 border-[#D4AF37]/55 shadow-[0_0_48px_rgba(212,175,55,0.3)] backdrop-blur-md',
    borderStyle: 'border-[#D4AF37]/55',
    glowStyle: 'shadow-[#D4AF37]/25',
    buttonStyle: 'bg-gradient-to-r from-[#D4AF37] to-[#B8960C] hover:from-[#FACC15] hover:to-[#D4AF37] text-slate-950 font-black',
    badgeStyle: 'bg-yellow-950/80 text-[#D4AF37] border-yellow-800/50',
    sidebarStyle: 'bg-[#040200]/97 border-r border-[#D4AF37]/15',
    vouchCardStyle: 'bg-[#0e0800] border-[#D4AF37]/55 shadow-[0_0_14px_rgba(212,175,55,0.18)]',
    parlayCardStyle: 'bg-[#0e0800] border-[#D4AF37]/55',
    resultCardStyle: 'bg-[#0b0600] border-[#D4AF37]/30',
    profileBorderStyle: 'border-[#D4AF37]',
    animationStyle: 'transition-all duration-300',
    shareCardStyle: 'from-yellow-950 to-[#040200]',
    unlockCondition: 'Free — available to all beta users',
    isPremium: false,
    isEarned: false,
    isSeasonal: false,
    cost: 0,
    badge: '👑 BETA GOLD',
    avatarAnimationClass: 'border-[#D4AF37] animate-pulse shadow-md shadow-[#D4AF37]/50',
    particleDemo: ['👑', '💰', '✨', '🏆'],
    fontFamily: 'font-sans',
    coverBg: 'from-[#D4AF37]/30 to-yellow-600/20',
    customAIPhrase: '👑 BETA GOLD PROOF · PREMIUM CAPPER CLUB',
    pageBg: 'bg-[#040200]',
    gridOverlay: 'opacity-12 bg-[radial-gradient(#D4AF37_1px,transparent_1px)] [background-size:22px_22px]',
    borderColor: 'border-[#D4AF37]/30',
    accentText: 'text-[#D4AF37]'
  },
  {
    id: 'beta-arcade-neon',
    name: 'Beta Arcade Neon',
    category: 'Retro',
    rarity: 'epic',
    description: '4-bit arcade sports feel — dark purple/black with cyan/pink/green accents. Fun, social, gamified. Free for all beta users.',
    background: 'bg-[#090314]',
    backgroundPattern: 'arcade',
    cardStyle: 'bg-[#14082e]/90 border-[#f472b6]/50 shadow-[0_0_22px_rgba(244,114,182,0.3)] backdrop-blur-md',
    borderStyle: 'border-[#f472b6]/50',
    glowStyle: 'shadow-[#f472b6]/20',
    buttonStyle: 'bg-gradient-to-r from-[#22d3ee] to-[#f472b6] hover:from-[#67e8f9] hover:to-[#f9a8d4] text-slate-950 font-black',
    badgeStyle: 'bg-[#1a0a2e] text-[#22d3ee] border-[#f472b6]/40',
    sidebarStyle: 'bg-[#090314]/95 border-r border-[#f472b6]/15',
    vouchCardStyle: 'bg-[#14082e] border-[#f472b6]/50 shadow-[0_0_12px_rgba(244,114,182,0.15)]',
    parlayCardStyle: 'bg-[#14082e] border-[#f472b6]/50',
    resultCardStyle: 'bg-[#10061f] border-[#f472b6]/30',
    profileBorderStyle: 'border-[#f472b6]',
    animationStyle: 'transition-all duration-200',
    shareCardStyle: 'from-[#1a0a2e] to-[#090314]',
    unlockCondition: 'Free — available to all beta users',
    isPremium: false,
    isEarned: false,
    isSeasonal: false,
    cost: 0,
    badge: '👾 BETA ARCADE',
    avatarAnimationClass: 'border-[#f472b6] shadow-md shadow-[#f472b6]/40',
    particleDemo: ['👾', '🎮', '⭐', '🪙'],
    fontFamily: 'font-mono',
    coverBg: 'from-[#f472b6]/30 to-[#22d3ee]/20',
    customAIPhrase: '👾 BETA ARCADE NEON · 4-BIT SPORTS ENERGY',
    pageBg: 'bg-[#090314]',
    gridOverlay: 'opacity-15 bg-[linear-gradient(rgba(244,114,182,0.1)_1px,transparent_1px)] [background-size:100%_6px]',
    borderColor: 'border-[#f472b6]/30',
    accentText: 'text-[#22d3ee] font-mono'
  }
];

export const BORDER_REGISTRY: ProfileBorder[] = [
  {
    id: 'default-cyber-ring',
    name: 'Default Cyber Ring',
    rarity: 'common',
    category: 'Core',
    animationType: 'none',
    unlockCondition: 'Standard default framework border',
    isPremium: false,
    isEarned: false,
    description: 'Sleek, transparent cyber outline with subtle teal highlights.',
    borderClass: 'border-cyan-500/80 border-2 shadow-[0_0_10px_rgba(6,182,212,0.3)]',
    overlayIcon: '⚡'
  },
  {
    id: 'neon-court-ring',
    name: 'Neon Court Ring',
    rarity: 'rare',
    category: 'Sport',
    themeId: 'neon-court',
    animationType: 'pulse',
    unlockCondition: 'Equip the Neon Court Theme or save an NBA bet',
    isPremium: false,
    isEarned: true,
    description: 'Hot court-orange neon border matching the energy of a live hardwood game.',
    borderClass: 'border-orange-500 border-3 animate-pulse shadow-[0_0_12px_rgba(249,115,22,0.5)]',
    overlayIcon: '🏀'
  },
  {
    id: 'diamond-glow-ring',
    name: 'Diamond Glow Ring',
    rarity: 'rare',
    category: 'Sport',
    themeId: 'diamond-glow',
    animationType: 'float',
    unlockCondition: 'Equip the Diamond Glow Theme or save an MLB bet',
    isPremium: false,
    isEarned: true,
    description: 'Frosted ballpark stadium floodlight outline with deep turf green overlays.',
    borderClass: 'border-emerald-500 border-2 animate-bounce shadow-[0_0_10px_rgba(16,185,129,0.4)]',
    overlayIcon: '⚾'
  },
  {
    id: '4bit-pixel-frame',
    name: '4-Bit Pixel Frame',
    rarity: 'rare',
    category: 'Retro',
    themeId: '4bit-arcade',
    animationType: 'none',
    unlockCondition: 'Unlocks under the Arcade series automatically',
    isPremium: false,
    isEarned: false,
    description: 'Bold, square pixelated frame reminiscent of arcade scoreboard grids.',
    borderClass: 'border-purple-500 border-4 rounded-none shadow-[0_0_12px_rgba(168,85,247,0.5)]',
    overlayIcon: '👾'
  },
  {
    id: '4bit-champion-frame',
    name: '4-Bit Champion Frame',
    rarity: 'legendary',
    category: 'Retro',
    themeId: '8bit-champion',
    animationType: 'sparkle',
    unlockCondition: 'Unlock the 8-Bit Champion theme with a 5-pick win streak',
    isPremium: false,
    isEarned: true,
    description: 'Staggered gold retro pixel stairs with high prestige rating symbols.',
    borderClass: 'border-yellow-500 border-4 rounded-none animate-pulse shadow-[0_0_18px_rgba(234,179,8,0.6)]',
    overlayIcon: '🏆'
  },
  {
    id: 'verified-capper-ring',
    name: 'Verified Capper Ring',
    rarity: 'verified',
    category: 'Trust',
    animationType: 'pulse',
    unlockCondition: 'Automatically equipped for certified verified accounts',
    isPremium: false,
    isEarned: true,
    description: 'Authentic sapphire blue ring overlaid with an official Vouch-ledger checkmark.',
    borderClass: 'border-blue-500 border-3 ring-1 ring-blue-400/40 shadow-[0_0_14px_rgba(59,130,246,0.55)]',
    overlayIcon: '✓'
  },
  {
    id: 'high-trust-ring',
    name: 'High Trust Ring',
    rarity: 'epic',
    category: 'Trust',
    animationType: 'float',
    unlockCondition: 'Maintained with a personal VouchEdge Trust Score of 75+',
    isPremium: false,
    isEarned: true,
    description: 'Glowing emerald circular flow highlighting bulletproof verification consistency.',
    borderClass: 'border-emerald-400 border-3 shadow-[0_0_15px_rgba(52,211,153,0.55)]',
    overlayIcon: '🛡️'
  },
  {
    id: 'hot-streak-flame-ring',
    name: 'Hot Streak Flame Ring',
    rarity: 'legendary',
    category: 'Flex',
    animationType: 'flame',
    unlockCondition: 'Triggered when your profile logs a 3+ win streak',
    isPremium: false,
    isEarned: true,
    description: 'Envelops your avatar in looping visual red-orange flame shadows.',
    borderClass: 'border-red-500 border-3 ring-2 ring-orange-500/50 shadow-[0_0_20px_rgba(239,68,68,0.7)] animate-pulse',
    overlayIcon: '🔥'
  },
  {
    id: 'parlay-winner-ring',
    name: 'Parlay Winner Ring',
    rarity: 'epic',
    category: 'Flex',
    animationType: 'sparkle',
    unlockCondition: 'Unlocks after hitting a verified parlay slips on Parlay Lab',
    isPremium: false,
    isEarned: true,
    description: 'Nostalgic deep violet loop with diamond-cut highlight reflections.',
    borderClass: 'border-fuchsia-500 border-3 shadow-[0_0_16px_rgba(217,70,239,0.5)]',
    overlayIcon: '💸'
  },
  {
    id: 'top-1-leaderboard-ring',
    name: 'Top 1% Leaderboard Ring',
    rarity: 'legendary',
    category: 'Trust',
    animationType: 'spin',
    unlockCondition: 'Earned exclusively by finishing on the Top 10 leaderboard',
    isPremium: false,
    isEarned: true,
    description: 'Radiant shifting spectrum crown ring reserved for absolute sports masters.',
    borderClass: 'border-gradient-to-r from-yellow-400 via-pink-500 to-indigo-500 border-4 shadow-[0_0_22px_rgba(244,63,94,0.6)] animate-pulse',
    overlayIcon: '👑'
  },
  {
    id: 'founder-early-user-ring',
    name: 'Founder / Early User Ring',
    rarity: 'founder',
    category: 'Core',
    animationType: 'none',
    unlockCondition: 'Given to initial early VouchEdge registered beta builders',
    isPremium: false,
    isEarned: true,
    description: 'Vintage brass texture stamped with cyan starbursts of structural integrity.',
    borderClass: 'border-cyan-400/80 border-4 shadow-[0_0_10px_rgba(34,211,238,0.4)]',
    overlayIcon: '🛰️'
  },
  {
    id: 'premium-subscriber-ring',
    name: 'Premium Subscriber Ring',
    rarity: 'epic',
    category: 'Premium',
    animationType: 'pulse',
    unlockCondition: 'Unlocks instantly for Pro subscription upgrades',
    isPremium: true,
    isEarned: false,
    description: 'Deep cobalt sapphire border embedded with cosmic purple indicators.',
    borderClass: 'border-indigo-500 border-3 ring-2 ring-purple-500/50 shadow-[0_0_18px_rgba(99,102,241,0.5)]',
    overlayIcon: '💎'
  },
  {
    id: 'ai-analyst-ring',
    name: 'AI Analyst Ring',
    rarity: 'seasonal',
    category: 'Premium',
    animationType: 'spin',
    unlockCondition: 'Unlocked for active users utilizing Trust Picks AI predictions',
    isPremium: true,
    isEarned: true,
    description: 'Flickering matrix nodes connected by digital glowing fibers.',
    borderClass: 'border-cyan-400 border-2 shadow-[0_0_14px_rgba(6,182,212,0.6)] animate-pulse',
    overlayIcon: '🔮'
  },
  {
    id: 'community-vouched-ring',
    name: 'Community Vouched Ring',
    rarity: 'common',
    category: 'Core',
    animationType: 'none',
    unlockCondition: 'Maintained with 20+ followers or 50+ total vouches',
    isPremium: false,
    isEarned: true,
    description: 'Warm, amber dotted ring indicating strong community-backed backing.',
    borderClass: 'border-amber-400/85 border-2 border-dashed shadow-[0_0_8px_rgba(251,191,36,0.3)]',
    overlayIcon: '🤝'
  },
  {
    id: 'gold-standard-ring',
    name: 'Gold Standard Ring',
    rarity: 'legendary',
    category: 'Premium',
    themeId: 'gold-standard',
    animationType: 'sparkle',
    unlockCondition: 'Equip the Gold Standard theme or purchase with credits',
    isPremium: true,
    isEarned: false,
    description: 'Heavy, liquid-gold capper crown frame of pristine performance.',
    borderClass: 'border-yellow-400 border-4 shadow-[0_0_20px_rgba(234,179,8,0.75)]',
    overlayIcon: '👑'
  },
  {
    id: 'proof-mode-verified-ring',
    name: 'Proof Mode Verified Ring',
    rarity: 'verified',
    category: 'Minimal',
    themeId: 'proof-mode',
    animationType: 'none',
    unlockCondition: 'Equip the Proof Mode Theme',
    isPremium: false,
    isEarned: false,
    description: 'Crisp black-and-white high-fidelity alignment check ring.',
    borderClass: 'border-slate-350 border-2 opacity-95',
    overlayIcon: '📊'
}];
