import React from 'react';
import Navbar from '../components/landing-v4/Navbar';
import AuditSummary from '../components/landing-v4/AuditSummary';
import AuditLedgerTable from '../components/landing-v4/AuditLedgerTable';
import { motion } from 'motion/react';

export default function AuditLedger() {
  return (
    <div className="min-h-screen bg-obsidian-900 text-white selection:bg-vouch-emerald/30 font-sans pb-32">
      <Navbar />
      
      <header className="pt-40 pb-20 px-6 border-b border-white/5 bg-obsidian-950">
        <div className="container mx-auto max-w-7xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-3xl"
          >
            <span className="terminal-text text-vouch-emerald mb-4 block">SYSTEM_AUDIT_LEDGER // v8.2_STABLE</span>
            <h1 className="text-5xl md:text-7xl font-bold tracking-tighter italic mb-8 leading-none">
              The Permanent <br />
              <span className="text-white/20">Evidence Record.</span>
            </h1>
            <p className="text-xl text-white/40 font-light leading-relaxed">
              Every hypothesis generated by VouchEdge is cryptographically hashed and stored. 
              We do not delete misses. We do not edit confidence. The record is immutable.
            </p>
          </motion.div>
        </div>
      </header>

      <main className="container mx-auto max-w-7xl px-6 -mt-10 relative z-10">
        <AuditSummary />
        <AuditLedgerTable />
        
        <div className="mt-20 p-12 glass-panel border-dashed border-white/10 text-center">
          <p className="terminal-text mb-4">End_of_Current_Buffer</p>
          <button className="px-8 py-4 border border-white/10 hover:bg-white/5 transition-all terminal-text text-white">
            Load_Historical_Archives [+]
          </button>
        </div>
      </main>

      <footer className="mt-40 py-20 border-t border-white/5">
        <div className="container mx-auto max-w-7xl px-6 flex justify-between items-center">
          <div className="terminal-text">
            NODE: US-EAST-PROXIMA-01 // STATUS: NOMINAL
          </div>
          <div className="flex gap-8">
            <span className="terminal-text hover:text-white cursor-pointer">API_DOCS</span>
            <span className="terminal-text hover:text-white cursor-pointer">SYSTEM_STATUS</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
