import { calculateAuroraScore } from "./score";
import { calculateConfidence } from "./confidence";
import { calculateVerdict } from "./verdict";
import { generateRecommendation } from "./recommendation";
import { generateSummary } from "./summary";

import type {
  AuroraAnalysis,
  AuroraEvidence,
  AuroraRisk,
  AuroraSource,
} from "./types";

export interface AnalyzeAuroraInput {
  sport: string;
  market: string;

  playerId?: string;
  playerName?: string;

  evidence: AuroraEvidence[];
  risks: AuroraRisk[];
  sources?: AuroraSource[];
}

export function analyzeAurora(
  input: AnalyzeAuroraInput,
): AuroraAnalysis {
  const auroraScore = calculateAuroraScore(
    input.evidence,
    input.risks,
  );

  const confidence = calculateConfidence(auroraScore);

  const verdict = calculateVerdict(auroraScore);

  const recommendation =
    generateRecommendation(verdict);

  const summary = generateSummary({
    playerName: input.playerName,
    verdict,
    confidence,
  });

  return {
    version: "1.0.0",
    generatedAt: new Date().toISOString(),

    sport: input.sport,
    market: input.market,

    playerId: input.playerId,
    playerName: input.playerName,

    verdict,

    auroraScore,
    confidence,

    evidence: input.evidence,
    risks: input.risks,

    recommendation,
    summary,

    explanation:
      "Generated by the Aurora Intelligence Engine.",

    sources: input.sources ?? [],
  };
}
